# Configuração Padrão do Sistema de Preparação de Manuscritos
# Versão 2.0

# Configurações Gerais
project_name: "Manuscript Publisher"
version: "2.0"
log_level: "INFO"

# Configurações de API (OpenAI)
# Defina OPENAI_API_KEY como variável de ambiente ou descomente abaixo
# openai_api_key: "sua-chave-aqui"
openai_model: "gpt-4o-mini"
openai_max_tokens: 3000
openai_temperature: 0.7

# Configurações de Processamento
enable_ai_enhancement: true
enable_ai_review: true
enable_diagram_generation: true
parallel_processing: false
max_workers: 4

# Configurações de Formatação
default_format: "A5"
default_font: "Times New Roman"
default_font_size: 12
default_line_spacing: 1.5

# Configurações de Elementos
generate_pre_textual: true
generate_post_textual: true
generate_glossary: true
generate_index: true

# Configurações de Revisão
check_grammar: true
check_style: true
check_consistency: true
check_references: true

# Configurações de Exportação
export_formats:
  - md
  - docx
  # - pdf  # Descomente para habilitar exportação PDF

include_metadata: true
include_diagrams: true

# Diretórios
templates_dir: "templates"
output_dir: "output"
cache_dir: ".cache"
