# Configuração para Manuais Técnicos

project_name: "Technical Manual"
version: "2.0"

# Configurações de API
openai_model: "gpt-4o-mini"
enable_ai_enhancement: true
enable_ai_review: true
enable_diagram_generation: true

# Formatação Técnica
default_format: "A4"
default_font: "Arial"
default_font_size: 11
default_line_spacing: 1.3

# Elementos Técnicos
generate_pre_textual: true
generate_post_textual: true
generate_glossary: true
generate_index: true

# Revisão Técnica
check_grammar: true
check_style: true
check_consistency: true
check_references: true

# Exportação
export_formats:
  - md
  - docx
  - pdf

include_metadata: true
include_diagrams: true
