OPENAI_API_KEY="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"
OPENAI_PROJECT_ID="proj_oo1ZBxHJKFIroaIRomyVt3Yy"
